In [ ]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [ ]:
%matplotlib inline

In [ ]:
df_survey = pd.read_csv("https://cocl.us/datascience_survey_data", index_col = 0)

In [ ]:
df_survey

In [ ]:
df_survey.sort_values(by=['Very interested'], ascending = False, inplace = True)

In [ ]:
df_survey

In [ ]:
figure = '(20,8)'

In [ ]:
import numpy as np

In [ ]:
df_perc = df_survey.copy(deep=True)

In [ ]:
df_perc

In [ ]:
df_perc = df_survey.copy(deep=True)
df_perc['Very interested'] = df_perc['Very interested'].apply(lambda x: round(x*(1/2233),4)*100)
df_perc['Somewhat interested'] = df_perc['Somewhat interested'].apply(lambda x: round(x*(1/2233),4)*100)
df_perc['Not interested'] = df_perc['Not interested'].apply(lambda x: round(x*(1/2233),4)*100)
df_perc

In [ ]:
ax = df_perc.plot(kind = 'bar', figsize=(20,8),color = ['#5cb85c', '#5bc0de','#d9534f'], width = 0.8)
ax.set_title('Percentage of Respondents\' Interest in Data Science Areas', fontsize = 16)
ax.legend(fontsize = 14)
plt.xticks(fontsize = 14)
#plt.yticks(fontsize = 14)
ax.set_yticklabels([])
ax.spines['top'].set_visible(False)
ax.spines['left'].set_visible(False)
ax.spines['right'].set_visible(False)
#ax.set_ylabel('% of Respondents', fontsize =14)
for p in ax.patches:
    width, height = p.get_width(), p.get_height()
    height = height.round(2)
    heightperc = str(height)+'%'
    x, y = p.get_xy()
    ax.annotate( (heightperc),(p.get_x()+.15*width, p.get_y() + height + 2.25), fontsize=14)
plt.show()

In [ ]:
df_sfcrime = pd.read_csv("https://cocl.us/sanfran_crime_dataset")

In [46]:
df_sfcrime.head(15)

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,120058272,WEAPON LAWS,POSS OF PROHIBITED WEAPON,Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212120
1,120058272,WEAPON LAWS,"FIREARM, LOADED, IN VEHICLE, POSSESSION OR USE",Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212168
2,141059263,WARRANTS,WARRANT ARREST,Monday,04/25/2016 12:00:00 AM,14:59,BAYVIEW,"ARREST, BOOKED",KEITH ST / SHAFTER AV,-122.388856,37.729981,"(37.7299809672996, -122.388856204292)",14105926363010
3,160013662,NON-CRIMINAL,LOST PROPERTY,Tuesday,01/05/2016 12:00:00 AM,23:50,TENDERLOIN,NONE,JONES ST / OFARRELL ST,-122.412971,37.785788,"(37.7857883766888, -122.412970537591)",16001366271000
4,160002740,NON-CRIMINAL,LOST PROPERTY,Friday,01/01/2016 12:00:00 AM,00:30,MISSION,NONE,16TH ST / MISSION ST,-122.419672,37.765050,"(37.7650501214668, -122.419671780296)",16000274071000
5,160002869,ASSAULT,BATTERY,Friday,01/01/2016 12:00:00 AM,21:35,NORTHERN,NONE,1700 Block of BUSH ST,-122.426077,37.788019,"(37.788018555829, -122.426077177375)",16000286904134
6,160003130,OTHER OFFENSES,PAROLE VIOLATION,Saturday,01/02/2016 12:00:00 AM,00:04,SOUTHERN,"ARREST, BOOKED",MARY ST / HOWARD ST,-122.405721,37.780879,"(37.7808789360214, -122.405721454567)",16000313026150
7,160003259,NON-CRIMINAL,FIRE REPORT,Saturday,01/02/2016 12:00:00 AM,01:02,TENDERLOIN,NONE,200 Block of EDDY ST,-122.411778,37.783981,"(37.7839805592634, -122.411778295992)",16000325968000
8,160003970,WARRANTS,WARRANT ARREST,Saturday,01/02/2016 12:00:00 AM,12:21,SOUTHERN,"ARREST, BOOKED",4TH ST / BERRY ST,-122.393357,37.775788,"(37.7757876218293, -122.393357241451)",16000397063010
9,160003641,MISSING PERSON,FOUND PERSON,Friday,01/01/2016 12:00:00 AM,10:06,BAYVIEW,NONE,100 Block of CAMERON WY,-122.387182,37.720967,"(37.7209669615499, -122.387181635995)",16000364175000
10,160086863,LARCENY/THEFT,ATTEMPTED THEFT FROM LOCKED VEHICLE,Friday,01/29/2016 12:00:00 AM,22:30,TARAVAL,NONE,1200 Block of 19TH AV,-122.477377,37.764478,"(37.7644781578695, -122.477376524003)",16008686306240
11,160004053,NON-CRIMINAL,"AIDED CASE, MENTAL DISTURBED",Saturday,01/02/2016 12:00:00 AM,13:30,TARAVAL,NONE,2200 Block of 21ST AV,-122.477960,37.745739,"(37.7457389429655, -122.477960327299)",16000405364020
12,160073014,OTHER OFFENSES,RESISTING ARREST,Monday,01/25/2016 12:00:00 AM,23:20,BAYVIEW,"ARREST, BOOKED",200 Block of HUNTERSPOINT BL,-122.376758,37.735697,"(37.7356970275482, -122.37675765553)",16007301427170
13,140776777,ASSAULT,AGGRAVATED ASSAULT WITH A GUN,Thursday,09/15/2016 12:00:00 AM,07:40,INGLESIDE,"ARREST, BOOKED",SILVER AV / CAMELLIA AV,-122.432326,37.729271,"(37.7292705199592, -122.432325871028)",14077677704011
14,160004069,BURGLARY,"BURGLARY,STORE UNDER CONSTRUCTION, FORCIBLE ENTRY",Saturday,01/02/2016 12:00:00 AM,01:43,CENTRAL,NONE,100 Block of SANSOME ST,-122.400909,37.791643,"(37.791642982384, -122.40090869889)",16000406905151

In [48]:
df_sfcrime.tail()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
150495,161061000,ASSAULT,BATTERY,Friday,12/30/2016 12:00:00 AM,21:01,PARK,NONE,OAK ST / STANYAN ST,-122.453982,37.771428,"(37.7714278595913, -122.453981622365)",16106100004134
150496,176000742,NON-CRIMINAL,LOST PROPERTY,Friday,12/30/2016 12:00:00 AM,08:00,CENTRAL,NONE,JACKSON ST / SANSOME ST,-122.401857,37.796626,"(37.7966261239618, -122.401857374739)",17600074271000
150497,176000758,LARCENY/THEFT,PETTY THEFT OF PROPERTY,Thursday,12/29/2016 12:00:00 AM,20:00,CENTRAL,NONE,PINE ST / TAYLOR ST,-122.412269,37.790673,"(37.7906727649886, -122.41226909106)",17600075806372
150498,176000764,LARCENY/THEFT,GRAND THEFT OF PROPERTY,Friday,12/30/2016 12:00:00 AM,10:00,CENTRAL,NONE,200 Block of STOCKTON ST,-122.406659,37.788275,"(37.7882745285785, -122.406658711008)",17600076406374
150499,179002868,OTHER OFFENSES,"FRAUDULENT GAME OR TRICK, OBTAINING MONEY OR P...",Friday,12/02/2016 12:00:00 AM,14:00,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",17900286809024

In [54]:
df_crimegroups=df_sfcrime.groupby(['PdDistrict']).count()

In [55]:
df_crimegroups

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,Resolution,Address,X,Y,Location,PdId
PdDistrict,,,,,,,,,,,,
BAYVIEW,14303,14303,14303,14303,14303,14303,14303,14303,14303,14303,14303,14303
CENTRAL,17666,17666,17666,17666,17666,17666,17666,17666,17666,17666,17666,17666
INGLESIDE,11594,11594,11594,11594,11594,11594,11594,11594,11594,11594,11594,11594
MISSION,19503,19503,19503,19503,19503,19503,19503,19503,19503,19503,19503,19503
NORTHERN,20100,20100,20100,20100,20100,20100,20100,20100,20100,20100,20100,20100
PARK,8699,8699,8699,8699,8699,8699,8699,8699,8699,8699,8699,8699
RICHMOND,8922,8922,8922,8922,8922,8922,8922,8922,8922,8922,8922,8922
SOUTHERN,28445,28445,28445,28445,28445,28445,28445,28445,28445,28445,28445,28445
TARAVAL,11325,11325,11325,11325,11325,11325,11325,11325,11325,11325,11325,11325
TENDERLOIN,9942,9942,9942,9942,9942,9942,9942,9942,9942,9942,9942,9942